  name: "OpenTofu checks"

  on:
    pull_request:
      paths-ignore:
        - .gitignore
        - "*.md"
        - CODEOWNERS
      branches:
        - main

  jobs:
    tofu-checks:
      name: "OpenTofu checks"
      runs-on: ubuntu-latest
      steps:
        - name: Get pull request ref
          id: sha
          uses: actions/github-script@v7
          with:
            result-encoding: string
            script: |
              const { owner, repo, number } = context.issue;
              const pr = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: number,
              });
              return pr.data.head.sha

        - name: Checkout
          uses: actions/checkout@v5
          with:
            ref: ${{ steps.sha.outputs.result }}

        - name: Setup OpenTofu
          uses: opentofu/setup-opentofu@v1

        - name: OpenTofu Format
          id: fmt
          run: tofu fmt -check -diff

        - name: OpenTofu Init
          id: init
          run: tofu init -backend=false

        - name: OpenTofu Validate
          id: validate
          run: tofu validate -no-color
