name: "OpenTofu apply"

concurrency: tofu-ci

on:
  push:
    paths-ignore:
      # YAML anchors doesn't seem to work in GitHub Actions, so we have to copy
      # this field.
      - .gitignore
      - "*.md"
      - CODEOWNERS
    branches:
      - main

jobs:
  tofu-apply:
    name: "OpenTofu apply"
    runs-on: ubuntu-latest
    env:
      TF_LOG: DEBUG
      # Google Cloud Storage state backend
      GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
      GOOGLE_APPLICATION_CREDENTIALS: '/tmp/tf-google-application-credentials.json'
      # GitHub provider
      TF_VAR_app_node_id: ${{ secrets.TF_VAR_APP_NODE_ID }}
      TF_VAR_github_app_id: ${{ secrets.GH_APP_ID }}
      TF_VAR_github_app_installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}
      TF_VAR_github_app_pem_file: ${{ secrets.GH_APP_PEM_FILE }}
    steps:
      - name: Write GCS credentials
        run: echo $GOOGLE_APPLICATION_CREDENTIALS_DATA > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu init
        id: init
        run: tofu init

      - name: OpenTofu validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu apply
        run: tofu apply -auto-approve
